### ISSUE TITLE
KiotaClientFactory doesn't build a httpclient that will work because it is missing auth middleware

### ISSUE THREAD

**Issue by darrelmiller** [microsoft/kiota-dotnet#270]
https://github.com/microsoft/kiota-http-dotnet/blob/eb76ee893324bd373462e98dfdafeba95762feff/src/KiotaClientFactory.cs#L36

This issue is related to this ADR https://github.com/microsoft/kiota/issues/3941

We need to think about building an AuthHandler middleware that can use our Kiota Auth Providers so that we can have native HttpClient experiences.  Otherwise, we can't satisfy this ADR https://github.com/microsoft/kiota/issues/3200

**Comment by baywet** [comment]
authored https://github.com/microsoftgraph/msgraph-sdk-design/pull/111 to help move this along

**Comment by lvde0** [comment]
I stumbled upon this issue since I have a custom "Token Refresh" middleware that tries to re-authenticate the request with the refreshed token. I was wondering if it's possible to access the `IAuthenticationProvider` somehow to do that? I mean I can still manually tweak the authorization header, but I think it would be cleaner to go via `IAuthenticationProvider`.

**Comment by baywet** [comment]
currently it's not, but with the new factory we'd be adding with this work, you could at least access it while initializing the middleware, and pass it to your custom middleware implementation.
We started the work in java https://github.com/microsoft/kiota-java/pull/1562
