### ISSUE TITLE
why get URL scheme "https+http" is not supported.

### ISSUE THREAD

**Issue by neozhu** [microsoft/kiota-dotnet#479]
in my aspire project : https://github.com/neozhu/cleanaspire
what should I do? Please give me some advice.

```c#
builder.Services.AddHttpClient("apiservice", client =>
{
    // This URL uses "https+http://" to indicate HTTPS is preferred over HTTP.
    // Learn more about service discovery scheme resolution at https://aka.ms/dotnet/sdschemes.
    client.BaseAddress = new("https+http://apiservice");
}
).AddHttpMessageHandler<CookieHandler>();
builder.Services.AddSingleton<ApiClient>(sp =>
{
    ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
    ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
    ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
    ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
    ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
    ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
    ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
    var settings = sp.GetRequiredService<IOptions<ClientAppSettings>>().Value;
    var httpClientFactory = sp.GetRequiredService<IHttpClientFactory>();
    var httpClient = httpClientFactory.CreateClient("apiservice");
    var authProvider = new AnonymousAuthenticationProvider();
    var requestAdapter = new HttpClientRequestAdapter(authProvider, httpClient: httpClient);
    var apiClient = new ApiClient(requestAdapter);
    //if (!string.IsNullOrEmpty(settings.ServiceBaseUrl))
    //{
    //    requestAdapter.BaseUrl = settings.ServiceBaseUrl;
    //}
    return apiClient;

});
```
![Image](https://github.com/user-attachments/assets/0bce0ba1-cb44-4677-97ca-112e3c258032)

![Image](https://github.com/user-attachments/assets/b4384acc-7441-44bc-b568-38616034db85)

**Comment by baywet** [comment]
Hi @neozhu 
Thank you for using kiota and for reaching out.

Am I correct that if you uncomment the lines setting the base url on the request adapter it start working properly?

Also, it should work properly if you do not set that "special value" in the http client base url, correct?

The base Url from the http client [is read in the request adapter](https://github.com/microsoft/kiota-dotnet/blob/7b2ded172b243447a7bb9bf93d8df0fa2089db27/src/http/httpClient/HttpClientRequestAdapter.cs#L52) and [passed to the RFC 6570 uri template](https://github.com/microsoft/kiota-dotnet/blob/7b2ded172b243447a7bb9bf93d8df0fa2089db27/src/http/httpClient/HttpClientRequestAdapter.cs#L565) in order to resolve the final URL.

Looking at the [documentation link from the comment](https://aka.ms/dotnet/sdschemes). Additionally, it seems that there should at least be a call to `AddServiceDiscovery` so things can be resolved (and I wonder whether they are resolved by a middleware handler during the request execution or ahead of that)
