### ISSUE TITLE
http - implement body inspection handler

### ISSUE THREAD

**Issue by baywet** [microsoft/kiota-dotnet#482]
specification https://github.com/microsoftgraph/msgraph-sdk-design/pull/116
make sure you update the [documentation](https://learn.microsoft.com/en-us/openapi/kiota/middleware?tabs=csharp#middleware-handlers) as well

**Comment by marcinjahn** [comment]
Let me take a stab at it and see what I can do

**Comment by AndrewZenith** [comment]
Hi, I've been using Kiota in C# now for talking to HMRC Services in the UK.  However, they are aaplication/xml content instead of json.  So, even though responses are (or can be) in the OpenApi yaml file, nothing is generated to get them.
It all works returning a stream of the content when an OK(200) is received.

I'm thinking this issue may solve my problem from the looks of it? If I can get the status code and body content then I can handle myself.

**Comment by baywet** [comment]
@AndrewZenith if the xml structure is described with a JSON schema, you'll get a much better experience by:
1. implementing IParseNode and ISerializationWriter (+ factories) for XML.
2. using the [structured mime types](https://learn.microsoft.com/en-us/openapi/kiota/using#--structured-mime-types--m) during generation
3. registering the new factories at runtime, so XML can be serialized/deserialized

Arguably it's a bit more work though.

And if you're willing to, you could even stand up a new project/package under the [kiota community](https://github.com/kiota-community/) organization, so others can also use the XML implementation.

**Comment by AndrewZenith** [comment]
> Arguably it's a bit more work though.

100+ classes for just one of the many responses.  I have the xsd's though.
